# Generated by Django 4.2.5 on 2023-10-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default='Dilip', max_length=50),
            preserve_default=False,
        ),
    ]
